#' A function to convert counts to frequencies.
#'
#' @param counts A merged count summary generated by mergeSummaries().
#' @details This function returns a table of counts converted to frequencies with an additional column
#' containing the sum of frequencies across samples.
#' @keywords BC32 processing convert frequencies
#' @export
#' @examples
#' freq <- countsToFreq(counts)

countsToFreq <- function(counts) {

  freq <- counts
  for (i in 2:(length(freq))) {
    freq[,i] <- 100*freq[,i]/sum(freq[,i])
  }

  # Add the sum of frequencies at the last column of the data frame
  sum.freq <- NULL
  for (i in 1:nrow(freq)) {
    sum.freq <- c(sum.freq, sum(freq[i,2:(length(freq))]))
  }
  freq$sum.freq <- sum.freq
  freq
}
